# Generated by Django 2.2.3 on 2019-12-08 00:30

from django.db import migrations


def forwards(apps, schema_editor):
    Doctor = apps.get_model('appointments', 'Doctor')

    doc_data = [
        ('Hibbert', 'Julius', 'hibbert@notablehealth.com'),
        ('Krieger', 'Algernop', 'krieger@notanlehealth.com')]

    for last_name, first_name, email in doc_data:
        Doctor.objects.create(first_name=first_name, last_name=last_name, email= email)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, lambda x,y: True),
    ]


