# Generated by Django 2.2.3 on 2019-12-08 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20191208_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appt_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='appt_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
